version: "3.3"
services:
  web:
    build: .
    volumes:
      - .:/var/app
      - ~/.bash_history:/root/.bash_history
      - ./config/database.yml:/var/config/database.yml
    ports:
      - "3000:3000"
    environment:
      PG_PASSWORD: password
    depends_on:
      - postgres
    tty: true
    stdin_open: true

  postgres:
    image: postgres:9.4.5
    environment:
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - dbdata:/var/lib/postgresql/data

volumes:
  dbdata: