version: "3.8"
services:
  web:
    build: .
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    volumes:
      - .:/app  
      - ~/.bash_history:/root/.bash_history
      - ./config/database.yml:/var/config/database.yml
      - yarn-volume:/app/node_modules
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL=postgres://postgres:password@postgres:5432/site_colmeia_development
    depends_on:
      - postgres
    tty: true
    stdin_open: true

  postgres:
    image: postgres:12.1-alpine
    environment:
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - dbdata:/var/lib/postgresql/data

volumes:
  yarn-volume:
  dbdata: